name: Dante Monteverde
favicon: null
layout_spectrum: 0.2892245282419026
typography_spectrum: 0.005236184690147638
title: Follow Dante
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7172336881048977
  lightness: 0.8378150595817715
  saturation: 0.5812443448230624
  rhythmicContrast: 0.191800873959437
purpose: []
